config/routes.rb
Rails.application.routes.draw do
  
  resources :movies
  resources :lessons
  resources :courses do
    resources :lessons, except: [:index, :show], controller: "courses/lessons"
    member do
      patch :generate_lessons
    end
  end

#  resources :course do
 #   member do
  #    patch :generate_lessons
   # end
  #end
  resources :services
  resources :classrooms
  devise_for :users
  resources :users, only: [:index, :show, :destroy, :edit, :update]
  root "static_pages#landing_page"
  get "privacy_policy", to: "static_pages#privacy_policy"
  get "calendar", to: "static_pages#calendar"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/service.rb
class Service < ApplicationRecord
    validates :name, presence: true
    validates_uniqueness_of :name, case_sentitive: false
    validates :duration, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 180}
    validates :client_price, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 10000}

    

    def to_s
        name
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: %i[ show edit update destroy ]

  # GET /services or /services.json
  def index
    @services = Service.all
  end

  # GET /services/1 or /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services or /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to service_url(@service), notice: "Service was successfully created." }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1 or /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to service_url(@service), notice: "Service was successfully updated." }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1 or /services/1.json
  def destroy
    @service.destroy

    respond_to do |format|
      format.html { redirect_to services_url, notice: "Service was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def service_params
      params.require(:service).permit(:name, :duration, :client_price)
    end
end

app/views/services/_form.html.erb
<%= simple_form_for(@service) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :duration %>
    <%= f.input :client_price %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<div class="card shadow">
  <div class="card-header">
    <h4>
      Edit
      Service
    </h4>
  </div>
  <div class="card-body">
    <%= render 'form', service: @service %>
  </div>
  <div class="card-footer">
    <%= link_to 'Cancel', @service %>
  </div>
</div>

app/views/services/index.html.erb
<h3>
  <div class="text-center">
    Services
    <div class="badge badge-info">
      <%= @services.count %>
    </div>
    <%= link_to "New service", new_service_path, class: 'btn btn-primary' %>
  </div>
</h3>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover table-sm table-light shadow">
    <thead>
      <tr>
        <th>Id</th>
    	  
        <th>Name</th>
        
        <th>Duration</th>
        
        <th>Client price</th>
        
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @services.each do |service| %>
        <%= content_tag :tr, id: dom_id(service), class: dom_class(service) do %>
          <td><%= link_to service.id, service %></td>
          
            <td><%= service.name %></td>
          
            <td><%= service.duration %></td>
          
            <td><%= service.client_price %></td>
          
          <td>
            <%= link_to 'Edit', edit_service_path(service), class: 'btn btn-sm btn-warning' %>
            <%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
          </td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/services/new.html.erb
<div class="card shadow">
  <div class="card-header">
    <h4>
      New
      Service
    </h4>
  </div>
  <div class="card-body">
    <%= render 'form', service: @service %>
  </div>
  <div class="card-footer">
    <%= link_to 'Cancel', services_path %>
  </div>
</div>

app/views/services/show.html.erb
<div class="card shadow">
  <div class="card-header">
    <h4>
      Service
    </h4>
  </div>
  <div class="card-body">
  
    <b>Name:</b>
    <%= @service.name %>
    <br>
  
    <b>Duration:</b>
    <%= @service.duration %>
    <br>
  
    <b>Client price:</b>
    <%= @service.client_price %>
    <br>
  
  </div>
  <div class="card-footer">
    <%= link_to 'Edit', edit_service_path(@service), class: 'btn btn-sm btn-warning' %>
    <%= link_to 'Destroy', @service, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
  </div>
</div>