config/routes.rb
Rails.application.routes.draw do
  
  resources :movies
  resources :lessons
  resources :courses do
    resources :lessons, except: [:index, :show], controller: "courses/lessons"
    member do
      patch :generate_lessons
    end
  end

#  resources :course do
 #   member do
  #    patch :generate_lessons
   # end
  #end
  resources :services
  resources :classrooms
  devise_for :users
  resources :users, only: [:index, :show, :destroy, :edit, :update]
  root "static_pages#landing_page"
  get "privacy_policy", to: "static_pages#privacy_policy"
  get "calendar", to: "static_pages#calendar"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/classroom.rb
class Classroom < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    validates_uniqueness_of :name, case_sentitive: false

    def to_s
        name
    end
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: %i[ show edit update destroy ]

  # GET /classrooms or /classrooms.json
  def index
    @classrooms = Classroom.all
  end

  # GET /classrooms/1 or /classrooms/1.json
  def show
  end

  # GET /classrooms/new
  def new
    @classroom = Classroom.new
  end

  # GET /classrooms/1/edit
  def edit
  end

  # POST /classrooms or /classrooms.json
  def create
    @classroom = Classroom.new(classroom_params)

    respond_to do |format|
      if @classroom.save
        format.html { redirect_to classroom_url(@classroom), notice: "Classroom was successfully created." }
        format.json { render :show, status: :created, location: @classroom }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classrooms/1 or /classrooms/1.json
  def update
    respond_to do |format|
      if @classroom.update(classroom_params)
        format.html { redirect_to classroom_url(@classroom), notice: "Classroom was successfully updated." }
        format.json { render :show, status: :ok, location: @classroom }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classrooms/1 or /classrooms/1.json
  def destroy
    @classroom.destroy

    respond_to do |format|
      format.html { redirect_to classrooms_url, notice: "Classroom was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classroom
      @classroom = Classroom.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def classroom_params
      params.require(:classroom).permit(:name)
    end
end

app/views/classrooms/_form.html.erb
<%= simple_form_for(@classroom) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/classrooms/edit.html.erb
<div class="card shadow">
  <div class="card-header">
    <h4>
      Edit
      Classroom
    </h4>
  </div>
  <div class="card-body">
    <%= render 'form', classroom: @classroom %>
  </div>
  <div class="card-footer">
    <%= link_to 'Cancel', @classroom %>
  </div>
</div>

app/views/classrooms/index.html.erb
<h3>
  <div class="text-center">
    Classrooms
    <div class="badge badge-info">
      <%= @classrooms.count %>
    </div>
    <%= link_to "New classroom", new_classroom_path, class: 'btn btn-primary' %>
  </div>
</h3>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover table-sm table-light shadow">
    <thead>
      <tr>
        <th>Id</th>
    	  
        <th>Name</th>
        
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @classrooms.each do |classroom| %>
        <%= content_tag :tr, id: dom_id(classroom), class: dom_class(classroom) do %>
          <td><%= link_to classroom.id, classroom %></td>
          
            <td><%= classroom.name %></td>
          
          <td>
            <%= link_to 'Edit', edit_classroom_path(classroom), class: 'btn btn-sm btn-warning' %>
            <%= link_to 'Destroy', classroom, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
          </td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/classrooms/new.html.erb
<div class="card shadow">
  <div class="card-header">
    <h4>
      New
      Classroom
    </h4>
  </div>
  <div class="card-body">
    <%= render 'form', classroom: @classroom %>
  </div>
  <div class="card-footer">
    <%= link_to 'Cancel', classrooms_path %>
  </div>
</div>

app/views/classrooms/show.html.erb
<div class="card shadow">
  <div class="card-header">
    <h4>
      Classroom
    </h4>
  </div>
  <div class="card-body">
  
    <b>Name:</b>
    <%= @classroom.name %>
    <br>
  
  </div>
  <div class="card-footer">
    <%= link_to 'Edit', edit_classroom_path(@classroom), class: 'btn btn-sm btn-warning' %>
    <%= link_to 'Destroy', @classroom, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
  </div>
</div>