config/routes.rb
Rails.application.routes.draw do
  
  resources :movies
  resources :lessons
  resources :courses do
    resources :lessons, except: [:index, :show], controller: "courses/lessons"
    member do
      patch :generate_lessons
    end
  end

#  resources :course do
 #   member do
  #    patch :generate_lessons
   # end
  #end
  resources :services
  resources :classrooms
  devise_for :users
  resources :users, only: [:index, :show, :destroy, :edit, :update]
  root "static_pages#landing_page"
  get "privacy_policy", to: "static_pages#privacy_policy"
  get "calendar", to: "static_pages#calendar"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  belongs_to :classroom
  belongs_to :course

  validates :status, presence: true

  STATUSES = [:planned, :confirmed, :cancelled]

  def self.statuses
    STATUSES.map { |status| [status, status]}
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[ show edit update destroy ]

  # GET /lessons or /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1 or /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons or /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to lesson_url(@lesson), notice: "Lesson was successfully created." }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1 or /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to lesson_url(@lesson), notice: "Lesson was successfully updated." }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1 or /lessons/1.json
  def destroy
    @lesson.destroy

    respond_to do |format|
      format.html { redirect_to lessons_url, notice: "Lesson was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lesson_params
      params.require(:lesson).permit(:user_id, :classroom_id, :course_id, :status, :start)
    end
end

app/views/lessons/_calendar.html.erb
<div class="card shadow">
  <div class="card-body">
    <div class="table-responsive">
    <%= month_calendar(events: @lessons, attribute: :start) do |date, lessons| %>
      <%= date %>

      <% lessons.each do |lesson| %>
        <div>
        Id:
        <%= link_to lesson.id, lesson_path(lesson) %>
        Course:
        <%= link_to lesson.course_id, lesson.course %>
        User:
        <%= link_to lesson.user_id, lesson.user %>
        Classroom:
        <%= link_to lesson.classroom_id, lesson.classroom %>
        Start:
        <%= link_to lesson.start.strftime("%H:%M") %>
        </div>

      <% end %>

    <% end %>
  </div>
    
  </div>
</div>





app/views/lessons/_form.html.erb
<%= simple_form_for(@lesson) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.association :classroom %>
    <%= f.association :course %>
    <br>
    <%= f.input :status, collection: Lesson.statuses, include_blank: false  %>
    <br>
    <%= f.input :start, minute_step: 15, start_year: Date.today.year - 1, end_year: Date.today.year + 1 %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<div class="card shadow">
  <div class="card-header">
    <h4>
      Edit
      Lesson
    </h4>
  </div>
  <div class="card-body">
    <%= render 'form', lesson: @lesson %>
  </div>
  <div class="card-footer">
    <%= link_to 'Cancel', @lesson %>
  </div>
</div>

app/views/lessons/index.html.erb
<h3>
  <div class="text-center">
    Lessons
    <div class="badge badge-info">
      <%= @lessons.count %>
    </div>
    <%= link_to "New lesson", new_lesson_path, class: 'btn btn-primary' %>
  </div>
</h3>

<%= render 'lessons/calendar' %>


<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover table-sm table-light shadow">
    <thead>
      <tr>
        <th>Id</th>
    	  
        <th>User</th>
        
        <th>Classroom</th>
        
        <th>Course</th>
        
        <th>Status</th>
        
        <th>Start</th>
        
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @lessons.each do |lesson| %>
        <%= content_tag :tr, id: dom_id(lesson), class: dom_class(lesson) do %>
          <td><%= link_to lesson.id, lesson %></td>
          
            <td><%= lesson.user %></td>
          
            <td><%= lesson.classroom %></td>
          
            <td><%= lesson.course %></td>
          
            <td><%= lesson.status %></td>
          
            <td><%= lesson.start %></td>
          
          <td>
            <%= link_to 'Edit', edit_lesson_path(lesson), class: 'btn btn-sm btn-warning' %>
            <%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
          </td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/lessons/new.html.erb
<div class="card shadow">
  <div class="card-header">
    <h4>
      New
      Lesson
    </h4>
  </div>
  <div class="card-body">
    <%= render 'form', lesson: @lesson %>
  </div>
  <div class="card-footer">
    <%= link_to 'Cancel', lessons_path %>
  </div>
</div>

app/views/lessons/show.html.erb
<div class="card shadow">
  <div class="card-header">
    <h4>
      Lesson
    </h4>
  </div>
  <div class="card-body">
  
    <b>User:</b>
    <%= @lesson.user %>
    <br>
  
    <b>Classroom:</b>
    <%= @lesson.classroom %>
    <br>
  
    <b>Course:</b>
    <%= @lesson.course_id %>
    <br>
  
    <b>Status:</b>
    <%= @lesson.status %>
    <br>
  
    <b>Start:</b>
    <%= @lesson.start %>
    <br>
  
  </div>
  <div class="card-footer">
    <%= link_to 'Edit', edit_lesson_path(@lesson), class: 'btn btn-sm btn-warning' %>
    <%= link_to 'Destroy', @lesson, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
  </div>
</div>